export const DECK = [
  // --- ANIMAL ---
  { id: 1, category: "Animal", question: "Dog", answer: "หมา" },
  { id: 2, category: "Animal", question: "Cat", answer: "แมว" },
  { id: 3, category: "Animal", question: "Bird", answer: "นก" },
  { id: 4, category: "Animal", question: "Fish", answer: "ปลา" },
  { id: 5, category: "Animal", question: "Elephant", answer: "ช้าง" },
  { id: 6, category: "Animal", question: "Tiger", answer: "เสือ" },
  { id: 7, category: "Animal", question: "Lion", answer: "สิงโต" },
  { id: 8, category: "Animal", question: "Bear", answer: "หมี" },
  { id: 9, category: "Animal", question: "Monkey", answer: "ลิง" },
  { id: 10, category: "Animal", question: "Snake", answer: "งู" },
  { id: 11, category: "Animal", question: "Horse", answer: "ม้า" },
  { id: 12, category: "Animal", question: "Cow", answer: "วัว" },
  { id: 13, category: "Animal", question: "Pig", answer: "หมู" },
  { id: 14, category: "Animal", question: "Chicken", answer: "ไก่" },
  { id: 15, category: "Animal", question: "Duck", answer: "เป็ด" },
  { id: 16, category: "Animal", question: "Turtle", answer: "เต่า" },
  { id: 17, category: "Animal", question: "Rabbit", answer: "กระต่าย" },
  { id: 18, category: "Animal", question: "Deer", answer: "กวาง" },
  { id: 19, category: "Animal", question: "Crocodile", answer: "จระเข้" },
  { id: 20, category: "Animal", question: "Frog", answer: "กบ" },
  { id: 21, category: "Animal", question: "Butterfly", answer: "ผีเสื้อ" },
  { id: 22, category: "Animal", question: "Bee", answer: "ผึ้ง" },
  { id: 23, category: "Animal", question: "Spider", answer: "แมงมุม" },
  { id: 24, category: "Animal", question: "Shark", answer: "ฉลาม" },
  { id: 25, category: "Animal", question: "Whale", answer: "วาฬ" },

  // --- PLANT ---
  { id: 26, category: "Plant", question: "Tree", answer: "ต้นไม้" },
  { id: 27, category: "Plant", question: "Flower", answer: "ดอกไม้" },
  { id: 28, category: "Plant", question: "Grass", answer: "หญ้า" },
  { id: 29, category: "Plant", question: "Leaf", answer: "ใบไม้" },
  { id: 30, category: "Plant", question: "Root", answer: "ราก" },
  { id: 31, category: "Plant", question: "Branch", answer: "กิ่งไม้" },
  { id: 32, category: "Plant", question: "Seed", answer: "เมล็ด" },
  { id: 33, category: "Plant", question: "Rose", answer: "กุหลาบ" },
  { id: 34, category: "Plant", question: "Lotus", answer: "ดอกบัว" },
  { id: 35, category: "Plant", question: "Sunflower", answer: "ทานตะวัน" },
  { id: 36, category: "Plant", question: "Orchid", answer: "กล้วยไม้" },
  { id: 37, category: "Plant", question: "Bamboo", answer: "ไผ่" },
  { id: 38, category: "Plant", question: "Fern", answer: "เฟิร์น" },
  { id: 39, category: "Plant", question: "Bush", answer: "พุ่มไม้" },
  { id: 40, category: "Plant", question: "Moss", answer: "มอส" },
  { id: 41, category: "Plant", question: "Cactus", answer: "กระบองเพชร" },
  { id: 42, category: "Plant", question: "Pine tree", answer: "ต้นสน" },
  { id: 43, category: "Plant", question: "Banana tree", answer: "ต้นกล้วย" },
  { id: 44, category: "Plant", question: "Coconut tree", answer: "ต้นมะพร้าว" },
  { id: 45, category: "Plant", question: "Weed", answer: "วัชพืช" },
  { id: 46, category: "Plant", question: "Fruit", answer: "ผลไม้" },
  { id: 47, category: "Plant", question: "Vegetable", answer: "ผัก" },
  { id: 48, category: "Plant", question: "Herb", answer: "สมุนไพร" },
  { id: 49, category: "Plant", question: "Vine", answer: "เถาวัลย์" },
  { id: 50, category: "Plant", question: "Bark", answer: "เปลือกไม้" },

  // --- NATURE ---
  { id: 51, category: "Nature", question: "Sun", answer: "พระอาทิตย์" },
  { id: 52, category: "Nature", question: "Moon", answer: "พระจันทร์" },
  { id: 53, category: "Nature", question: "Star", answer: "ดาว" },
  { id: 54, category: "Nature", question: "Sky", answer: "ท้องฟ้า" },
  { id: 55, category: "Nature", question: "Cloud", answer: "เมฆ" },
  { id: 56, category: "Nature", question: "Rain", answer: "ฝน" },
  { id: 57, category: "Nature", question: "Wind", answer: "ลม" },
  { id: 58, category: "Nature", question: "Storm", answer: "พายุ" },
  { id: 59, category: "Nature", question: "Snow", answer: "หิมะ" },
  { id: 60, category: "Nature", question: "Mountain", answer: "ภูเขา" },
  { id: 61, category: "Nature", question: "River", answer: "แม่น้ำ" },
  { id: 62, category: "Nature", question: "Ocean", answer: "มหาสมุทร" },
  { id: 63, category: "Nature", question: "Sea", answer: "ทะเล" },
  { id: 64, category: "Nature", question: "Lake", answer: "ทะเลสาบ" },
  { id: 65, category: "Nature", question: "Waterfall", answer: "น้ำตก" },
  { id: 66, category: "Nature", question: "Cave", answer: "ถ้ำ" },
  { id: 67, category: "Nature", question: "Rock", answer: "หิน" },
  { id: 68, category: "Nature", question: "Sand", answer: "ทราย" },
  { id: 69, category: "Nature", question: "Soil / Dirt", answer: "ดิน" },
  { id: 70, category: "Nature", question: "Forest", answer: "ป่า" },
  { id: 71, category: "Nature", question: "Island", answer: "เกาะ" },
  { id: 72, category: "Nature", question: "Fire", answer: "ไฟ" },
  { id: 73, category: "Nature", question: "Water", answer: "น้ำ" },
  { id: 74, category: "Nature", question: "Ice", answer: "น้ำแข็ง" },
  { id: 75, category: "Nature", question: "Earthquake", answer: "แผ่นดินไหว" },

  // --- PLACE ---
  { id: 76, category: "Place", question: "House", answer: "บ้าน" },
  { id: 77, category: "Place", question: "School", answer: "โรงเรียน" },
  { id: 78, category: "Place", question: "Hospital", answer: "โรงพยาบาล" },
  { id: 79, category: "Place", question: "Temple", answer: "วัด" },
  { id: 80, category: "Place", question: "Market", answer: "ตลาด" },
  { id: 81, category: "Place", question: "Shop / Store", answer: "ร้านค้า" },
  { id: 82, category: "Place", question: "Bank", answer: "ธนาคาร" },
  { id: 83, category: "Place", question: "Park", answer: "สวนสาธารณะ" },
  { id: 84, category: "Place", question: "Airport", answer: "สนามบิน" },
  { id: 85, category: "Place", question: "Train Station", answer: "สถานีรถไฟ" },
  { id: 86, category: "Place", question: "Restaurant", answer: "ร้านอาหาร" },
  { id: 87, category: "Place", question: "Hotel", answer: "โรงแรม" },
  { id: 88, category: "Place", question: "Office", answer: "สำนักงาน" },
  { id: 89, category: "Place", question: "Library", answer: "ห้องสมุด" },
  { id: 90, category: "Place", question: "Cinema", answer: "โรงภาพยนตร์" },
  { id: 91, category: "Place", question: "Zoo", answer: "สวนสัตว์" },
  { id: 92, category: "Place", question: "Beach", answer: "ชายหาด" },
  { id: 93, category: "Place", question: "City", answer: "เมือง" },
  { id: 94, category: "Place", question: "Village", answer: "หมู่บ้าน" },
  { id: 95, category: "Place", question: "Street / Road", answer: "ถนน" },
  { id: 96, category: "Place", question: "Bridge", answer: "สะพาน" },
  { id: 97, category: "Place", question: "Gym", answer: "โรงยิม" },
  { id: 98, category: "Place", question: "Museum", answer: "พิพิธภัณฑ์" },
  { id: 99, category: "Place", question: "Post Office", answer: "ไปรษณีย์" },
  {
    id: 100,
    category: "Place",
    question: "Police Station",
    answer: "สถานีตำรวจ",
  },
];
